### ISSUE TITLE
Warning in msbuild

### ISSUE THREAD

**Issue by warpech** [Polyjuice/SignIn#4]
When building SignIn app in msbuild (I think it also happens in VS), I get the following warning:

> "c:\PolyjuiceProjects\Polyjuice\SignIn\src\SignIn\SignIn.csproj" (default target)
 (7:2) ->
(ResolveAssemblyReferences target) ->
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5):
 warning MSB3245: Could not resolve this reference. Could not locate the assembly
 "Newtonsoft.Json". Check to make sure the assembly exists on disk. If this refer
ence is required by your code, you may get compilation errors. [c:\PolyjuiceProje
cts\Polyjuice\SignIn\src\SignIn\SignIn.csproj]

Is Newtonsoft.Json actually required?

**Comment by alemoi** [comment]
> Is Newtonsoft.Json actually required?

As I understand @chrhol completely replaced it with `DynamicJson`. But we should ask Christian if he confirms this.

**Comment by warpech** [comment]
I don't think this is related to Starcounter's `DynamicJson` but rather to @miyconst work on Json Web Token. 

Reference to Newtonsoft.Json was added in commit https://github.com/Polyjuice/SignIn/commit/654bf82a1422c803139bdf9e7da709a72dc6f00e

The Json Web Token code was since that time commented out, but the reference remains

**Comment by miyconst** [comment]
Done.
